#!/bin/bash
URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"
curl -s -o "$OUTPUT_FILE" "$URL" 2> "$ERROR_FILE"
if [ $? -eq 0 ] && [ -s "$OUTPUT_FILE" ]; then 
	echo "Data saved to $OUTPUT_FILE"
else
	echo "❌Failed to fetch data. see $ERROR_FILE for details"
fi
